# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0006_add_user_editable_to_data_source'),
        ('users', '0010_fill_is_general_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_orghierarchy.Organization'),
        ),
    ]
