---
version: '3'
services:
  runserver:
    build: .
    command: /usr/bin/python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code:Z
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    links:
      - postgresql
    environment:
# Project specific env vars for this project:
# Service level env vars:
      - HTTPS=off
      - LANG=en_US.utf8
      - LC_ALL=en_US.UTF-8
      - LC_LANG=en_US.UTF-8
      - DJANGO_SETTINGS_MODULE=respa.development
# Infra env vars:
      - PYTHONUNBUFFERED=1
      - SSH_AUTH_SOCK
      - GIT_AUTHOR_EMAIL
      - GIT_AUTHOR_NAME
      - GIT_COMMITTER_EMAIL
      - GIT_COMMITTER_NAME
    networks:
      - network
    depends_on:
      - postgresql
    stdin_open: true
    tty: true

  postgresql:
    image: mdillon/postgis:9.5-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    # volumes:
    #   - ./psql:/var/lib/postgresql:Z
    ports:
      - '5432:5432'
    networks:
      - network


volumes:
  postgresql:

networks:
  network:
