# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 18:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0067_add_reservation_confirmed_notification_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='access code')),
                ('driver_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_control_grants', to='resources.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, help_text='Identifier of resource in the access control system (if any)', max_length=100, null=True, verbose_name='identifier')),
                ('driver_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_control_resources', to='resources.Resource', verbose_name='resource')),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('driver', models.CharField(choices=[('sipass', 'Siemens SiPass')], max_length=30)),
                ('reservation_leeway', models.PositiveIntegerField(blank=True, help_text='How many minutes before and after the reservation the access will be allowed', null=True, verbose_name='reservation leeway')),
                ('driver_config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Driver-specific configuration', null=True)),
                ('driver_data', django.contrib.postgres.fields.jsonb.JSONField(editable=False, help_text='Internal driver data', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='kulkunen.AccessControlSystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accesscontrolresource',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='kulkunen.AccessControlSystem', verbose_name='system'),
        ),
        migrations.AddField(
            model_name='accesscontrolgrant',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='kulkunen.AccessControlResource'),
        ),
        migrations.AddField(
            model_name='accesscontrolgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='kulkunen.AccessControlUser'),
        ),
        migrations.AlterUniqueTogether(
            name='accesscontrolresource',
            unique_together=set([('system', 'resource')]),
        ),
    ]
