# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0006_add_user_editable_to_data_source'),
        ('resources', '0072_reservable_min_and_max_days_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_orghierarchy.Organization'),
        ),
    ]
