# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-01 05:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0075_resource_use_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='recipient_for_resources', to=settings.AUTH_USER_MODEL, verbose_name='Users to receive emails from confirmed reservations'),
        ),
    ]
